prod:
  .settings:
    logging_enabled: off
    error_reporting:        '<?php echo E_ALL | E_STRICT ?>'
    no_script_name:		off
    cache: off
    standard_helpers:       [Number, Partial, Cache, Form, Date, I18N, JavascriptBase, Object]

dev:
  .settings:
    error_reporting:        '<?php echo E_ALL | E_STRICT ?>'
    web_debug:              on
    cache:                  off
    stats:                  off
    no_script_name:         off
    standard_helpers:       [Number, Partial, Cache, Form, Date, I18N, JavascriptBase, Object]

test:
  .settings:
    error_reporting:        '<?php echo E_ALL | E_STRICT & E_NOTICE ?>'
    cache:                  off
    stats:                  off
    web_debug:              off

all:
  .actions:
    default_module:         engine
    default_action:         index

    error_404_module:       main
    error_404_action:       error404

    login_module:           login
    login_action:           index

    secure_module:          utente
    secure_action:          rinnova

  .settings:
    compat_10: on
    default_culture: it
    i18n: on
    standard_helpers:       [Number, Partial, Cache, Form, Date, I18N, JavascriptBase, Object]
    cache:                  off
    rich_text_fck_js_dir:  js/FCKeditor
    rich_text_fck_base_dir:  progetti/pimonline/web/js/FCKeditor
